# Generated by Django 2.0.6 on 2018-06-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='author',
        ),
    ]
